<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Cronotus.Presentation</name>
    </assembly>
    <members>
        <member name="M:Cronotus.Presentation.Controllers.AuthenticationController.RegisterUser(Shared.DataTransferObjects.UserForRegistrationDto)">
            <summary>
            Registers a new user
            </summary>
            <param name="userForRegistration"></param>
            <response code="201">User created successfully</response>
            <response code="400">A bad request was sent and user creation was unsuccessfull</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.AuthenticationController.Authenticate(Shared.DataTransferObjects.UserForAuthenticationDto)">
            <summary>
            Logs in a user
            </summary>
            <param name="userForAuthentication"></param>
            <response code="200">Login was successfull</response>
            <response code="401">The credentials were incorrect thus the login failed</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.EventController.GetAllEvents">
            <summary>
            Returns a preview of all events
            </summary>
            <response code="200">The request was successful.</response>
            <response code="500">There was an internal server error thus the request was unsuccessful.</response>
            <returns>An array of event previews</returns>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.EventController.GetEvent(System.Guid)">
            <summary>
            Returns a single event by id
            </summary>
            <param name="id"></param>
            <response code="200">The request was successful and the event by the given id was returned.</response>
            <response code="404">The event by the given id was not found.</response>
            <response code="500">There was an internal server error causing the request to be unsuccessful.</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.EventController.CreateEvent(Shared.DataTransferObjects.EventForCreationDto)">
            <summary>
            Creates a new event
            </summary>
            <param name="eventDto"></param>
            <response code="201">The event was successfully created.</response>
            <response code="404">No sport/organizer was found to be bounded to event. Event creation failed.</response> 
            <response code="400">The input object was not in acceptable form causing a bad request.</response>
            <response code="500">There was an internal server error causing the request to be unsuccessful.</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.EventController.DeleteEvent(System.Guid)">
            <summary>
            Deletes an event by id
            </summary>
            <param name="id"></param>
            <response code="204">The event was deleted successfully.</response>
            <response code="404">The event by the given id does not exist. Could not be deleted.</response>
            <response code="500">There was an internal server error causing the request to be unsuccessful.</response>
            <returns></returns>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.OrganizerController.CreateOrganizer(Shared.DataTransferObjects.OrganizerForCreationDto)">
            <summary>
            Creates a new organizer
            </summary>
            <param name="organizerDto"></param>
            <returns code="201">The object was created successfully.</returns>
            <returns code="400">Bad request sent. The request was not successful.</returns>
            <returns code="409">The request was not successful because an organizer already exists with the given user id.</returns>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.ProfileController.GetProfile(System.Guid)">
            <summary>
            Gets a profile by id
            </summary>
            <param name="id"></param>
            <returns>A single user profile.</returns>
            <response code="200">User profile returned successfully</response>
            <response code="404">User was not found by the given id.</response>
            <response code="500">An internall server error occured and the request was unsuccessful.</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.ProfileController.PartiallyUpdateProfile(System.Guid,Microsoft.AspNetCore.JsonPatch.JsonPatchDocument{Shared.DataTransferObjects.ProfileForUpdateDto})">
            <summary>
            Partially updates a profile
            </summary>
            <param name="id"></param>
            <param name="patchDoc"></param>
            <returns>No return object</returns>
            <response code="204">The request was successful and the object was partially updated.</response>
            <response code="400">The patch document is null, the update was not successful.</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.ProfileController.DeleteProfile(System.Guid)">
            <summary>
            Deletes a profile by id
            </summary>
            <param name="id"></param>
            <returns>No return object.</returns>
            <response code="204">The profile was deleted successfully.</response>
            <response code="500">There was an internal server error, the request was unsuccessful.</response>
        </member>
        <member name="M:Cronotus.Presentation.Controllers.TokenController.Refresh(Shared.DataTransferObjects.TokenDto)">
            <summary>
            Creates a new token set
            </summary>
            <param name="tokenDto"></param>
            <returns>TokenDto object containing an acces token and a refresh token.</returns>
        </member>
    </members>
</doc>
